[package]
name    = "computer-graphics-from-scratch-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow     = "1.0.93"
bytemuck   = "1.19.0"
cgmath     = "0.18.0"
env_logger = "0.11.5"
png        = "0.17.14"
